CREATE TABLE  FEE_STUDENT
   (ROLLNO int NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255),
	EMAIL VARCHAR(255),
    SEX VARCHAR(255),
    COURSE varchar(255),
    FEE int,
    PAID int,
    DUE int,
	ADDRESS VARCHAR(255),
	CONTACT VARCHAR(255), 
	 CONSTRAINT FEE_STUDENT_PK PRIMARY KEY (ROLLNO)
   )