CREATE TABLE  FEE_ACCOUNTANT
   (ID int NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255),
	EMAIL VARCHAR(255),
	PASSWORD VARCHAR(255),
	ADDRESS VARCHAR(255),
	CONTACT VARCHAR(255), 
	 CONSTRAINT FEE_ACCOUNTANT_PK PRIMARY KEY (ID)
   )